project_id = "qiljmluitzwqlotlxxat"

[functions.orchestration-agent]
verify_jwt = false

[functions.course-writer-agent] 
verify_jwt = false

[functions.attachments-presign]
verify_jwt = false

[functions.publish-course-to-s3]
verify_jwt = false