// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiljmluitzwqlotlxxat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpbGptbHVpdHp3cWxvdGx4eGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NDgwOTAsImV4cCI6MjA3MjQyNDA5MH0.IfdEdRHQTW7vfNRfkobQliWcnXS1Mt6mmhDt8mT2xJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});